apiVersion: skaffold/v2beta12
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/*
build:
  local:
    push: false
  artifacts:
    - image: officialrashid/project8:2
      context: .
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "app"
            dest: "."
